apiVersion: v1
kind: Secret
metadata:
  name: {{ include "solar-dach.fullname" . }}
  labels:
    {{- include "solar-dach.labels" . | nindent 4 }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
